# Generated by Django 2.1.7 on 2019-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=30)),
                ('Type_Of_Emergency', models.CharField(max_length=500)),
                ('Exact_Location', models.CharField(max_length=100)),
                ('Time_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('message', models.TextField(max_length=5000)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
