# Generated by Django 2.1.7 on 2019-04-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0002_delete_emergency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Msgs',
        ),
    ]
