# Generated by Django 2.2.1 on 2019-05-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0003_auto_20190428_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msgs',
        ),
    ]
