# Generated by Django 2.2.1 on 2019-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medics', '0004_delete_msgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='')),
                ('Username', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=60)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
