# Generated by Django 2.1.7 on 2019-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0002_auto_20190327_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=30)),
                ('services', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('hometown', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Newsupdate',
        ),
    ]
