# Generated by Django 2.1.7 on 2019-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0005_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
