# Generated by Django 2.1.7 on 2019-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0006_firstaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('Time_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
