# Generated by Django 2.1.7 on 2019-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0007_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='Location',
        ),
        migrations.AddField(
            model_name='emergency',
            name='Exact_Location',
            field=models.CharField(default=54, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='Type_Of_Emergency',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
