# Generated by Django 2.1.7 on 2019-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0008_auto_20190413_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
