# Generated by Django 2.1.7 on 2019-04-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medexpert', '0009_auto_20190424_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('home_town', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='clinics',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='firstaid',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='website',
            field=models.URLField(),
        ),
    ]
