# Generated by Django 2.1.7 on 2019-04-28 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medexpert', '0010_auto_20190428_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registration2',
        ),
    ]
