# Generated by Django 2.1.7 on 2019-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0011_auto_20190428_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration2',
            name='physical_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration2',
            name='date_of_birth',
            field=models.DateField(default=-10800),
        ),
        migrations.AlterField(
            model_name='registration2',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registration2',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
