# Generated by Django 2.2.1 on 2019-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0012_auto_20190428_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('message', models.TextField(max_length=5000)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
