# Generated by Django 2.2.1 on 2019-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0013_msgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Clinics',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='Registration2',
        ),
    ]
