# Generated by Django 2.2.1 on 2019-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0015_auto_20190522_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='Email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='Subject',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
