# Generated by Django 2.2.1 on 2019-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medexpert', '0017_auto_20190522_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7),
        ),
    ]
